services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    # Do NOT publish the DB port in production

  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"  # access via http://YOUR_VM_IP/

volumes:
  dbdata: